## BERT 파인튜닝

### ✅ `distilbert-base-uncased` 모델 정보

| 항목                     | `distilbert-base-uncased`          |
|------------------------|----------------------------------|
| 🔢 모델 타입               | Encoder (BERT 계열)                  |
| 📦 사전학습 목적             | 마스킹된 언어 모델 (Masked LM)         |
| 🧠 파라미터 수              | 약 66M                              |
| 🏗️ 레이어 수              | 6                                  |
| 🧩 히든 크기 (Hidden Size) | 768                                |
| 🔁 어텐션 헤드 수            | 12                                 |
| 📏 최대 시퀀스 길이           | 512 tokens                         |
| 📄 토크나이저 타입            | WordPiece (BERT형)                  |
| 💬 생성 능력               | ❌ (비생성형, 분류에 적합)              |
| ⚙️ 사용 예시               | 텍스트 분류, 감정 분석 등               |
| ⚡ 연산 효율성               | 빠름 (BERT의 경량화 버전)              |

# 📌 자연어 처리 텍스트 분류 파이프라인 전체 흐름 이해하기

이 코드는 영화 리뷰(imdb) 텍스트가 **긍정인지 부정인지 분류하는 자연어 처리(NLP)** 예제입니다.  

---

## ✅ 단계 1: 문제 정의 - 텍스트를 분류하는 모델 만들기
- 목적: 영화 리뷰를 보고 **긍정(좋다)**인지 **부정(싫다)**인지 자동으로 판단하는 모델을 만든다.
- 입력: 영화 리뷰 텍스트 (예: `"This movie was awesome!"`)
- 출력: 0 (부정) 또는 1 (긍정)

> 🎯 예를 들면, 모델에게 `"It was amazing!"`이라는 문장을 주면 → `1(긍정)`이라고 판단하게 만드는 것이 목표입니다.

---

## ✅ 단계 2: 데이터 준비 - 영화 리뷰 데이터를 가져오기
- 사용하는 데이터셋: **IMDB 영화 리뷰 데이터셋**
- 예제에서는 **20개 리뷰만 샘플로 사용**하고, 이 중 80%는 학습용, 20%는 테스트용으로 나눕니다.

> 🧩 왜 데이터를 나눌까?
> - **학습 데이터**로 모델을 훈련시키고  
> - **테스트 데이터**로 모델이 잘 학습되었는지 검증합니다.

---

## ✅ 단계 3: 텍스트 전처리 - 단어를 숫자로 바꾸기
- 컴퓨터는 글자가 아니라 숫자를 이해합니다.
- 그래서 `"I loved the movie"` 같은 문장을 숫자 토큰으로 바꿔야 합니다.
- 이 작업을 도와주는 것이 바로 **토크나이저(Tokenzier)** 입니다.

> ✨ 비유하자면, 문장을 ‘레고 블록’처럼 잘게 쪼개고, 각각에 번호를 붙이는 과정입니다.

---

## ✅ 단계 4: 모델 준비 - 사전학습된 똑똑한 모델 불러오기
- 우리는 처음부터 모델을 만드는 게 아니라, 이미 영어를 어느 정도 학습해둔 모델(**DistilBERT**)을 가져옵니다.
- 이 모델에 "긍정/부정 분류"라는 **새로운 임무를 학습시키는 것**입니다. 이를 **파인튜닝(Fine-tuning)**이라고 합니다.

> 🧠 쉽게 말해, "기초 영어는 이미 배운 친구에게 감정 분석이라는 새 과목을 가르치는 것"입니다.

---

## ✅ 단계 5: 모델 훈련 - 데이터로 학습시키기
- 앞에서 준비한 텍스트(숫자 형태)와 라벨(긍정/부정)을 가지고 모델을 학습합니다.
- 학습은 30번 반복해서 진행됩니다 (30 에폭).

> 🚀 학습이란? 모델이 "이 문장이 긍정인지 부정인지" 스스로 맞추도록 훈련시키는 과정입니다.

---

## ✅ 단계 6: 예측하기 - 새로운 문장에 대해 모델이 판단하도록 하기
- 학습이 끝난 모델에 새로운 문장을 넣어보면, 긍정인지 부정인지 판단해줍니다.
- 예: `"It was great to see John Ritter"` → 모델이 **긍정**이라고 판단하면 `1`을 반환합니다.

---

## ✅ 단계 7 : 모델저장

In [1]:
## PC에서는
# pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu126
# pip install transformers datasets huggingface_hub
# pip install scikit-learn==1.6.1 accelerate>=1.1.0
# pip install transformers[torch]

##세션 다시 시작 필요
!pip install -q transformers datasets huggingface_hub


# 🤖 Hugging Face 라이브러리 설치
# transformers: 사전학습된 NLP 모델을 쉽게 사용할 수 있게 해주는 라이브러리
# datasets: 다양한 자연어처리용 데이터셋을 손쉽게 불러올 수 있는 라이브러리

In [2]:
import torch
print(torch.__version__)

2.11.0+cu130

In [3]:
import transformers
import datasets
import huggingface_hub
import fsspec # datasets가 내부적으로 설치해 줌

print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("huggingface_hub:", huggingface_hub.__version__)
print("fsspec:", fsspec.__version__)

transformers: 5.18.0
datasets: 4.8.5
huggingface_hub: 1.33.0
fsspec: 2025.12.0

In [5]:
# from tensorflow.keras.datasets import imdb
# (X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)
from datasets import load_dataset

dataset = load_dataset('stanfordnlp/imdb',
                       split="train[:50]" # 이거 빼면 25000개 train, 25000개 test가져옴
                       )
dataset = dataset.train_test_split(test_size=0.2)
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 40
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 10
    })
})

In [ ]:
sample = dataset['train'][7]
print(f"📝 리뷰 내용:\n{sample['text']}\n")
print(f"🏷️ 라벨 (0=부정, 1=긍정): {sample['label']}")

📝 리뷰 내용:
Its not the cast. A finer group of actors, you could not find. Its not the setting. The director is in love with New York City, and by the end of the film, so are we all! Woody Allen could not improve upon what Bogdonovich has done here. If you are going to fall in love, or find love, Manhattan is the place to go. No, the problem with the movie is the script. There is none. The actors fall in love at first sight, words are unnecessary. In the director's own experience in Hollywood that is what happens when they go to work on the set. It is reality to him, and his peers, but it is a fantasy to most of us in the real world. So, in the end, the movie is hollow, and shallow, and message-less.

🏷️ 라벨 (0=부정, 1=긍정): 0

In [ ]:
# ✅ 2. 모델 및 토크나이저 준비
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
# 🔍 포인트: 토크나이저란? → 텍스트를 숫자 토큰으로 바꾸는 역할
# "나는 배가 고프다" → [101, 1432, 2234, 1678, 102] ← 이런 식으로 숫자로 바꿔줘야 모델이 이해 가능
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)
# 🔍 distilbert-base-uncased: BERT를 경량화한 모델 (빠르고 정확도도 준수)
# 포인트: 사전학습(pretrained)된 모델이므로, 적은 데이터로도 빠르게 학습 가능
# ✅ 3. 데이터 전처리 (텍스트를 숫자 토큰으로 변환)
def tokenize(batch):
    return tokenizer(batch['text'],
                     truncation=True, # 모델이 처리할 최대길이 보다 길면 짤라
                     padding=True) # 제일 긴문장에 맞춰
# 🔍 포인트: tokenizer 함수로 모든 리뷰 텍스트를 숫자 토큰으로 바꿉니다
# - truncation=True: 문장이 너무 길면 자르고
# - padding=True: 짧은 문장은 0으로 채워 길이를 맞춰줍니다
dataset = dataset.map(tokenize, batched=True)
# 🔍 map 함수: 전체 데이터셋에 대해 위 tokenize 함수를 한꺼번에 적용
# - batched=True: 여러 데이터를 동시에 처리해서 속도 향상

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/40 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

In [ ]:
tokenizer(dataset['train'][7]['text'], padding=True, truncation=True)
# input_ids : 모델이 실제로 읽는 입력(101부터 102까지 문장 첫부분부터 끝부분)
# token_type_ids : 첫번째 문장
# attention_mask : 전부 1(패딩이 없음 → 모든 위치가 실제 토큰)

{'input_ids': [101, 2049, 2025, 1996, 3459, 1012, 1037, 26954, 2177, 1997, 5889, 1010, 2017, 2071, 2025, 2424, 1012, 2049, 2025, 1996, 4292, 1012, 1996, 2472, 2003, 1999, 2293, 2007, 2047, 2259, 2103, 1010, 1998, 2011, 1996, 2203, 1997, 1996, 2143, 1010, 2061, 2024, 2057, 2035, 999, 13703, 5297, 2071, 2025, 5335, 2588, 2054, 22132, 5280, 12303, 2038, 2589, 2182, 1012, 2065, 2017, 2024, 2183, 2000, 2991, 1999, 2293, 1010, 2030, 2424, 2293, 1010, 7128, 2003, 1996, 2173, 2000, 2175, 1012, 2053, 1010, 1996, 3291, 2007, 1996, 3185, 2003, 1996, 5896, 1012, 2045, 2003, 3904, 1012, 1996, 5889, 2991, 1999, 2293, 2012, 2034, 4356, 1010, 2616, 2024, 14203, 1012, 1999, 1996, 2472, 1005, 1055, 2219, 3325, 1999, 5365, 2008, 2003, 2054, 6433, 2043, 2027, 2175, 2000, 2147, 2006, 1996, 2275, 1012, 2009, 2003, 4507, 2000, 2032, 1010, 1998, 2010, 12746, 1010, 2021, 2009, 2003, 1037, 5913, 2000, 2087, 1997, 2149, 1999, 1996, 2613, 2088, 1012, 2061, 1010, 1999, 1996, 2203, 1010, 1996, 3185, 2003, 8892, 1010, 1998, 8467, 1010, 1998, 4471, 1011, 2625, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
print(dataset['train'][1]["input_ids"])

[101, 2017, 2031, 2000, 19837, 8226, 23531, 2130, 2065, 2017, 2123, 1005, 1056, 3391, 2215, 2000, 1010, 1037, 2158, 2040, 14684, 6826, 2015, 2041, 5166, 5469, 2044, 5166, 5469, 2000, 2625, 2084, 14727, 16466, 1012, 2021, 7906, 2006, 2725, 2009, 2035, 1996, 2168, 1012, 2130, 1996, 2431, 1011, 18627, 8489, 2084, 20626, 2010, 3409, 2668, 3152, 2003, 2445, 24665, 6784, 28392, 1998, 1045, 1005, 1049, 2004, 5905, 1997, 2023, 2004, 3087, 1012, 8226, 5373, 9020, 2000, 5466, 2242, 5875, 2046, 1996, 4666, 1010, 1037, 15708, 2801, 1010, 1037, 12849, 6559, 2100, 2839, 1010, 3649, 1010, 2021, 2302, 1996, 5029, 2000, 2202, 2009, 2582, 2084, 2918, 2504, 1010, 2002, 16803, 2006, 1996, 4378, 2000, 3013, 2032, 2070, 19840, 1998, 9120, 2009, 2005, 2054, 2009, 2003, 1998, 2054, 2009, 2071, 2022, 1012, 3533, 5292, 13327, 3723, 3957, 1037, 24462, 1998, 2200, 6057, 2836, 2004, 1041, 10609, 25733, 4027, 1998, 2049, 1037, 4923, 2000, 23531, 2008, 2002, 2064, 3168, 2008, 2023, 5976, 7384, 2735, 2003, 2183, 2000, 2147, 2306, 1996, 7705, 1997, 1996, 2143, 1012, 2746, 2000, 1037, 3674, 2595, 2379, 2017, 1010, 1999, 1037, 5903, 5304, 1010, 4873, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
# ✅ 4. 훈련 설정 및 Trainer 구성
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score
# 정확도 계산 함수
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = logits.argmax(-1)
    acc = accuracy_score(labels, predictions)
    return {'accuracy':acc}

# 파라미터 설정
args = TrainingArguments(
    output_dir="test",    # 모델이 저장될 경로
    per_device_train_batch_size=8, # 학습 시 배치 크기 (GPU 하나당 8개씩 처리)
    num_train_epochs=15, # 학습 반복 횟수(데이터셋을 15번 반복해서 학습)
    report_to="none",    # wandb, tensorboard 등 외부 로깅 툴 비활성화
    logging_steps=3      # 💡 몇 step마다 로그 출력할지
)
trainer = Trainer(
    model=model,  # 사용할 모델
    args=args,  # 훈련 설정값
    train_dataset=dataset["train"],  # 학습용 데이터셋
    eval_dataset=dataset["test"],  # 검증용 데이터셋
    compute_metrics=compute_metrics,  # 💡 정확도 계산 함수 추가
)
# 🔍 포인트: Trainer는 Hugging Face에서 제공하는 편리한 훈련 도구
# 복잡한 학습 코드 없이도 손쉽게 훈련 가능

In [ ]:
# ✅ 5. 파인튜닝 실행 (모델 학습) : GPU없이는 45분 / GPU 45초
trainer.train()
# 🔍 포인트: 위 한 줄만으로 모델이 훈련됨! (사전학습된 모델을 우리가 준비한 데이터에 맞춰 미세조정)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=75, training_loss=0.04151583383480708, metrics={'train_runtime': 39.5316, 'train_samples_per_second': 15.178, 'train_steps_per_second': 1.897, 'total_flos': 79480439193600.0, 'train_loss': 0.04151583383480708, 'epoch': 15.0})

In [ ]:
result = trainer.evaluate()
print(result)

{'eval_loss': 0.0011457193177193403, 'eval_accuracy': 1.0}

In [ ]:
# ✅ 6. 학습된 모델로 실제 예측 수행
text = "I would put this at the top of my list of films in the category of unwatchable trash!"
inputs = tokenizer(text, return_tensors="pt",
                    #truncation=True,
                    #padding=True
                   ).to('cuda')
# 🔍 포인트: 새 문장을 토큰화한 후, GPU로 보내줌 (".to('cuda')" 필수)
# "pt": PyTorch 텐서 형식으로 변환
# import torch
# with torch.no_grad():# 추론할 땐 gradient 계산 끄기 (메모리 절약)
output = model(**inputs)
print(output)

SequenceClassifierOutput(loss=None, logits=tensor([[ 3.1572, -3.0810]], device='cuda:0', grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
label = output.logits.argmax(dim=-1).item()
# 🔍 포인트: 모델 출력(logits)은 [부정 점수, 긍정 점수] 형태의 벡터
# argmax(-1): 가장 높은 점수의 인덱스 (0 또는 1)를 예측값으로 사용

print("긍정" if label == 1 else "부정")
# 🔍 최종 결과 출력: 긍정인지 부정인지 해석해서 보여줌

부정

In [ ]:
inputs

{'input_ids': tensor([[  101,  1045,  2052,  2404,  2023,  2012,  1996,  2327,  1997,  2026,
          2862,  1997,  3152,  1999,  1996,  4696,  1997,  4895, 18866,  3085,
         11669,   999,   102]], device='cuda:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
       device='cuda:0')}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ✅ 7. 모델 저장
save_dir = "./imdb-distilbert-full"     # 저장할 폴더 이름 (모델 이름과 겹치지 않게)
save_dir = "/content/drive/MyDrive/Colab Notebooks/imdb-distilbert-full"
trainer.save_model(save_dir)            # 학습된 모델 가중치(model.safetensors) + 설정(config.json) 저장
tokenizer.save_pretrained(save_dir)     # 토크나이저 파일 저장 (Trainer에 안 넘겼으니 직접 저장)

import os
print(os.listdir(save_dir))             # 저장된 파일 목록 확인

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

['config.json', 'model.safetensors', 'training_args.bin', 'tokenizer_config.json', 'tokenizer.json']

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

load_dir = "./imdb-distilbert-full"
load_dir = '/content/drive/MyDrive/Colab Notebooks/imdb-distilbert-full'

tokenizer = AutoTokenizer.from_pretrained(load_dir)                       # 저장한 토크나이저 불러오기
model = AutoModelForSequenceClassification.from_pretrained(load_dir)      # 학습된 모델 불러오기

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()                                       # 추론 모드 (드롭아웃 끄기)

text = "I would put this at the top of my list of films in the category of unwatchable trash!"
inputs = tokenizer(text, return_tensors="pt", truncation=True).to(device)  # 모델과 같은 장치로

with torch.no_grad():                              # 추론이라 기울기 계산 안 함 (메모리 절약)
    logits = model(**inputs).logits

pred = logits.argmax(-1).item()                    # 점수가 큰 쪽의 번호
print(pred, model.config.id2label[pred])           # 예: 0 negative

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

0 LABEL_0

In [ ]:
text = "I would put this at the top of my list of films in the category of unwatchable trash!"
inputs = tokenizer(text, return_tensors="pt",
                    #truncation=True,
                    #padding=True
                   ).to('cuda')
# 🔍 포인트: 새 문장을 토큰화한 후, GPU로 보내줌 (".to('cuda')" 필수)
# "pt": PyTorch 텐서 형식으로 변환
# import torch
# with torch.no_grad():# 추론할 땐 gradient 계산 끄기 (메모리 절약)
output = model(**inputs)
print(output)

SequenceClassifierOutput(loss=None, logits=tensor([[ 3.1572, -3.0810]], device='cuda:0', grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
from transformers import pipeline

clf = pipeline("text-classification", model=load_dir)   # 폴더 경로만 넣으면 끝
print(clf("This movie was absolutely wonderful!"))
# [{'label': 'positive', 'score': 0.9...}]  ← id2label을 넣었을 때

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[{'label': 'LABEL_0', 'score': 0.9964451193809509}]