In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
.inner_cell{font-size:20pt;}
div.text_cell_render pre code {font-size:20pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

<font size="6" color="red">ch11. 데이터프레임과 시리즈(Pandas)</font>
- pip install pandas (아나콘다 프롬프트)

# 1절. 판다스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지. 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계
- 1차원 구조를 갖는 시리즈 / 2차원 구조를 갖는 데이터 프레임을 제공
- 판다스 장점 : 
        데이터 프레임 생성, 파일 i/o, 레이블링, 부분데이터추출, 크기변경(행이나 열삽입 삭제),
        데이터 분할, 병합, 데이터 정렬, 결측치 처리, 피벗과 언피벗 등이 용이
- https://pandas.pydata.org/docs/reference/index.html (API reference)

In [2]:
import pandas as pd
pd.__version__

'1.5.3'

In [9]:
data = pd.read_json('data/ch09_member1.json'
                   # , encoding='utf-8' 판다스 read함수의 기본 encoding은 utf-8
                   )
display(data)
print(type(data))

  name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

<class 'pandas.core.frame.DataFrame'>

In [10]:
member4 = pd.read_csv('data/ch09_member4.csv') # 해더가 있는 csv
member4

  name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구