In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
.inner_cell{font-size:20pt;}
div.text_cell_render pre code {font-size:20pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

<font size="6" color="red">ch11. 데이터프레임과 시리즈(Pandas)</font>
# 9절. 데이터 그룹화 및 집계

In [8]:
from statsmodels.api import datasets
iris = datasets.get_rdataset('iris').data
iris.iloc[[0,49,50,99,100,149]]

     Sepal.Length  ...     Species
0             5.1  ...      setosa
49            5.0  ...      setosa
50            7.0  ...  versicolor
99            5.7  ...  versicolor
100           6.3  ...   virginica
149           5.9  ...   virginica

[6 rows x 5 columns]

## 9.1 Group by
    cf. pivot_table

In [17]:
iris.groupby('Species').sum()

            Sepal.Length  ...  Petal.Width
Species                   ...
setosa             250.3  ...         12.3
versicolor         296.8  ...         66.3
virginica          329.4  ...        101.3

[3 rows x 4 columns]

In [22]:
# 1) 그룹화 방법 1
#    df.groupby(by=[그룹핑할열이름])[함수적용해서출력할열들].기초통계함수()
    # [함수적용해서출력할열들] 생략시 모든 열이 적용
iris_grouped = iris.groupby('Species')
iris_grouped = iris.groupby(iris.Species)
iris_grouped_sum = iris_grouped.sum()
iris_grouped_sum   # iris.groupby('Species').sum()

            Sepal.Length  ...  Petal.Width
Species                   ...
setosa             250.3  ...         12.3
versicolor         296.8  ...         66.3
virginica          329.4  ...        101.3

[3 rows x 4 columns]

In [24]:
# setosa, virginica의 집계만
iris_grouped_sum.loc[['setosa','virginica']]

           Sepal.Length  ...  Petal.Width
Species                  ...
setosa            250.3  ...         12.3
virginica         329.4  ...        101.3

[2 rows x 4 columns]

In [25]:
print(iris_grouped_sum.index)

Index(['setosa', 'versicolor', 'virginica'], dtype='object', name='Species')

In [28]:
iris_grouped_sum.reset_index(inplace=True) #인덱스를 컬럼으로 편입시킴

In [29]:
iris_grouped_sum

      Species  ...  Petal.Width
0      setosa  ...         12.3
1  versicolor  ...         66.3
2   virginica  ...        101.3

[3 rows x 5 columns]

In [31]:
# setosa, virginica의 집계만
iris_grouped_sum[(iris_grouped_sum.Species=='setosa') | (iris_grouped_sum.Species=='virginica')]
iris_grouped_sum[iris_grouped_sum.Species.isin(['setosa', 'virginica'])]

     Species  ...  Petal.Width
0     setosa  ...         12.3
2  virginica  ...        101.3

[2 rows x 5 columns]

In [34]:
# 1) 그룹화 방법 1-1 : 그룹핑할 때 index를 컬럼 데이터로 편입(reset_index()가 필요X)
#    df.groupby(by=[그룹핑할열이름], as_index=False)[함수적용해서출력할열들].기초통계함수()
    # [함수적용해서출력할열들] 생략시 모든 열이 적용
iris.groupby(iris['Species'], as_index=False).sum()
iris.groupby(iris.Species, as_index=False).sum()
iris.groupby('Species', as_index=False).sum()

      Species  ...  Petal.Width
0      setosa  ...         12.3
1  versicolor  ...         66.3
2   virginica  ...        101.3

[3 rows x 5 columns]

In [38]:
# 종별 Sepal.Length와 Sepal.Width의 평균
iris.groupby('Species').mean()[['Sepal.Length','Sepal.Width']]
iris.groupby('Species')[['Sepal.Length','Sepal.Width']].mean()

            Sepal.Length  Sepal.Width
Species
setosa             5.006        3.428
versicolor         5.936        2.770
virginica          6.588        2.974

In [43]:
# 종별 Sepal.Length의 합계
iris.groupby('Species')['Sepal.Length'].sum() # 결과가 시리즈(1차원)

Species
setosa        250.3
versicolor    296.8
virginica     329.4
Name: Sepal.Length, dtype: float64

In [40]:
# 종별 Sepal.Length의 합계
iris.groupby('Species')['Sepal.Length',].sum()
iris.groupby('Species')[['Sepal.Length']].sum() # 결과가 데이터프레임(2차원)

            Sepal.Length
Species
setosa             250.3
versicolor         296.8
virginica          329.4

In [52]:
# 그룹화방법1
    # df.groupby(by=[그룹핑할열이름들])[함수적용해서출력할열들].함수명()
# 그룹화방법2
    # df.pivot_table(index='그룹핑할열이름들',
    #                values=['함수적용해서출력할열들'],
    #                aggfunc=함수명(기본값:mean) 
    #               )
iris.pivot_table(index='Species',
                # values=['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']
                # aggfunc='mean'
                )

            Petal.Length  ...  Sepal.Width
Species                   ...
setosa             1.462  ...        3.428
versicolor         4.260  ...        2.770
virginica          5.552  ...        2.974

[3 rows x 4 columns]