In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
.inner_cell{font-size:20pt;}
div.text_cell_render pre code {font-size:20pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

<font size="6" color="red">ch11. 데이터프레임과 시리즈(Pandas)</font>
- pip install pandas (아나콘다 프롬프트)

# 1절. 판다스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지. 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계
- 1차원 구조를 갖는 시리즈 / 2차원 구조를 갖는 데이터 프레임을 제공
- 판다스 장점 : 
        데이터 프레임 생성, 파일 i/o, 레이블링, 부분데이터추출, 크기변경(행이나 열삽입 삭제),
        데이터 분할, 병합, 데이터 정렬, 결측치 처리, 피벗과 언피벗 등이 용이
- https://pandas.pydata.org/docs/reference/index.html (API reference)

In [2]:
import pandas as pd
pd.__version__

'1.5.3'

In [9]:
data = pd.read_json('data/ch09_member1.json'
                   # , encoding='utf-8' 판다스 read함수의 기본 encoding은 utf-8
                   )
display(data)
print(type(data))

  name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

<class 'pandas.core.frame.DataFrame'>

In [10]:
member4 = pd.read_csv('data/ch09_member4.csv') # 해더가 있는 csv
member4

  name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

In [15]:
member1 = pd.read_csv('data/ch09_member1.csv',
                     header=None,
                     names=['이름','나이','메일','주소'])
member1

    이름  나이                메일        주소
0  홍길동  20  kildong@hong.com   서울시 관악구
1  김길동  40  kimdong@hong.com  서울시 영등포구
2  신길동  30  sindong@hong.com   서울시 동작구

In [16]:
pd.read_hdf('data/ch09_iris.h5', key="iris")

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 2절. 데이터 프레임 만들기
## 2.1 딕셔너리를 이용해서 데이터 프레임 만들기

In [18]:
d = {'kor':[100,90], 'mat':[95,99]}
df = pd.DataFrame(data=d)
df

   kor  mat
0  100   95
1   90   99

In [19]:
df.to_dict() # 데이터프레임을 딕셔너리로

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [20]:
df.to_numpy() # 데이터프레임을 넘파이배열

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [24]:
d = [{'kor':100, 'mat':95.0}, 
     {'kor':90, 'mat':99}]
df = pd.DataFrame(d) #데이터 프레임의 열은 동일 자료형
df

   kor   mat
0  100  95.0
1   90  99.0

In [25]:
df.dtypes # 데이터 프레임의 열별 타입

kor      int64
mat    float64
dtype: object

In [26]:
df.info() # ★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 160.0 bytes

In [38]:
import numpy as np
df['kor'] = df['kor'].astype(np.float64) # 데이터프레임의 열 타입 변경
df

     kor   mat
0  100.0  95.0
1   90.0  99.0

In [42]:
d = [{'kor':100, 'mat':100},
     {'kor':90,  'mat':99},
     {'kor':83,  'eng':85}]
df = pd.DataFrame(data=d)
df

   kor    mat   eng
0  100  100.0   NaN
1   90   99.0   NaN
2   83    NaN  85.0

In [40]:
type(np.nan) # 결측치의 타입 : float

float

In [46]:
# 결측치는 int로 형변환 불가

## 2.2 리스트를 이용해서 데이터프레임 만들기

In [47]:
kor = [100, 90, 80, 70, 60]
mat = [90, 80, 81, 71, 61]
df = pd.DataFrame({'kor': kor, 'mat':mat})
df

   kor  mat
0  100   90
1   90   80
2   80   81
3   70   71
4   60   61

In [50]:
pd.DataFrame(np.c_[kor, mat], columns=['kor','mat'])

   kor  mat
0  100   90
1   90   80
2   80   81
3   70   71
4   60   61

In [53]:
l = [[100,90], [70,80]]
pd.DataFrame(l, columns=['국어','수학'])

    국어  수학
0  100  90
1   70  80

- data.go.kr에서 "상가상권 정보" 다운로드 / "민간 아파트 분양가격" 다운로드

In [61]:
%ls c:\ai\downloads\shareData\상가정보\

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: E67D-C334

 c:\ai\downloads\shareData\상가정보 디렉터리

2026-07-14  오후 05:39    <DIR>          .
2026-07-14  오후 05:39    <DIR>          ..
2025-11-03  오전 12:45             1,011 [필독]파일열람방법.txt
2026-04-27  오전 11:10        61,321,696 소상공인시장진흥공단_상가(상권)정보_강원_202603.csv
2026-04-27  오전 11:10       367,852,181 소상공인시장진흥공단_상가(상권)정보_경기_202603.csv
2026-04-27  오전 11:10        92,474,293 소상공인시장진흥공단_상가(상권)정보_경남_202603.csv
2026-04-27  오전 11:10        76,309,810 소상공인시장진흥공단_상가(상권)정보_경북_202603.csv
2026-04-27  오전 11:10        40,031,721 소상공인시장진흥공단_상가(상권)정보_광주_202603.csv
2026-04-27  오전 11:10        61,825,564 소상공인시장진흥공단_상가(상권)정보_대구_202603.csv
2026-04-27  오전 11:10        41,866,930 소상공인시장진흥공단_상가(상권)정보_대전_202603.csv
2026-04-27  오전 11:10        84,329,596 소상공인시장진흥공단_상가(상권)정보_부산_202603.csv
2026-04-27  오전 11:10       292,646,735 소상공인시장진흥공단_상가(상권)정보_서울_202603.csv
2026-04-27  오전 11:10         9,651,297 소상공인시장진흥공단_상가(상권)정보_세종_202603.csv
2026-04-27  오전 11:10        28,285,232 소상공인시장진흥공단_상가(상권)정보_울산_202603.csv
2026-04-27  오전 11:10        74,007,608 소상공인시장진흥공단_상가(상권)정보_인천_202603.csv
2026-04-27  오전 11:10        53,165,985 소상공인시장진흥공단_상가(상권)정보_전남_202603.csv
2026-04-27  오전 11:10        56,632,709 소상공인시장진흥공단_상가(상권)정보_전북_202603.csv
2026-04-27  오전 11:10        32,746,698 소상공인시장진흥공단_상가(상권)정보_제주_202603.csv
2026-04-27  오전 11:10        66,764,669 소상공인시장진흥공단_상가(상권)정보_충남_202603.csv
2026-04-27  오전 11:10        50,941,247 소상공인시장진흥공단_상가(상권)정보_충북_202603.csv
              18개 파일       1,490,854,982 바이트
               2개 디렉터리  367,056,535,552 바이트 남음

In [64]:
df = pd.read_csv(r'c:\ai\downloads\shareData\상가정보\소상공인시장진흥공단_상가(상권)정보_세종_202603.csv',
                # encoding='utf-8', sep=',',
                 nrows=30, # 처음 30행만 가져오기
                 low_memory=False, # 데이터 용량이 클 경우 기입
                )
df.shape # 30행 39열

(30, 39)

In [65]:
df.head(1) # 상위 1행

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220813963449,레인카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4473025021101010001038753,NaN,세종특별자치시 세종특별자치시 조치원읍 조치원8길 16,339883.0,30027,NaN,지,NaN,127.300453,36.600906

In [72]:
# 판다스 디스플레이스 옵션
pd.options.display.max_columns = 39 # 39열까지 display
pd.options.display.max_rows = 40 # 40행까지 display

In [74]:
df.head(2).T

                                       0                                1
상가업소번호              MA010120220813963449             MA010120220805872513
상호명                                 레인카페                             수와마을
지점명                                  NaN                              NaN
상권업종대분류코드                             I2                               I2
상권업종대분류명                              음식                               음식
상권업종중분류코드                           I212                             I201
상권업종중분류명                           비알코올                                한식
상권업종소분류코드                         I21201                           I20101
상권업종소분류명                              카페                           백반/한정식
표준산업분류코드                          I56229                           I56111
표준산업분류명                     기타 비알코올 음료점업                       한식 일반 음식점업
시도코드                                  36                               36
시도명                              세종특별자치시                          세종특별자치시
시군구코드                              36110                            36110
시군구명                             세종특별자치시                          세종특별자치시
행정동코드                           36110250                         36110250
행정동명                                조치원읍                             조치원읍
법정동코드                         3611025021                       3611025030
법정동명                                조치원읍                             조치원읍
지번코드                 3611025021101010001              3611025030103790016
대지구분코드                                 1                                1
대지구분명                                 대지                               대지
지번본번지                                101                              379
지번부번지                                1.0                             16.0
지번주소       세종특별자치시 세종특별자치시 조치원읍 원리 101-1  세종특별자치시 세종특별자치시 조치원읍 죽림리 379-16
도로명코드                       361104574473                     361103258034
도로명           세종특별자치시 세종특별자치시 조치원읍 조치원8길         세종특별자치시 세종특별자치시 조치원읍 충현로
건물본번지                                 16                               75
건물부번지                                NaN                              1.0
건물관리번호         4473025021101010001038753        4473025030103790016042253
건물명                                  NaN                              NaN
도로명주소      세종특별자치시 세종특별자치시 조치원읍 조치원8길 16    세종특별자치시 세종특별자치시 조치원읍 충현로 75-1
구우편번호                           339883.0                         339884.0
신우편번호                              30027                            30034
동정보                                  NaN                              NaN
층정보                                    지                              NaN
호정보                                  NaN                              NaN
경도                            127.300453                       127.296263
위도                             36.600906                        36.595303

## 2.3 read_csv

In [5]:
# (1) CSV 파일 불러오기(기본값)
import pandas as pd
member = pd.read_csv('data/ch11_member.csv')
member

   Name  Age          Email  Address       Birth
0   홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1   홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2   홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3   홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4   홍길중   23   mid@hong.com   부산시 중구  1999-01-30
5  #홍길뜽   24    non@not.com      없는구  2000-01-01

In [6]:
member.info() # ★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      int64
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes

In [7]:
# 문자형으로 변환
member['Age'] = member['Age'].astype('str')
member.dtypes

Name       object
Age        object
Email      object
Address    object
Birth      object
dtype: object

In [8]:
# 숫자형으로 변환
import numpy as np
member['Age'] = member['Age'].astype('float32')
member['Age'] = member['Age'].astype(np.float32)
member['Age'] = pd.to_numeric(member['Age'], 
                  downcast='integer', # 빼면 int32나 float64로 자동 변환
                  errors='coerce')   # 숫자로 바꿀 수 없는 데이터는 결측치로 변환 ex) 3,000
member.dtypes

Name       object
Age          int8
Email      object
Address    object
Birth      object
dtype: object

In [9]:
# 문자로 읽어들인 Birth를 datetime형으로
member['Birth'] = member['Birth'].astype('datetime64[ns]')# 1999-01-01
member = member.astype({'Birth':'datetime64[ns]', 'Age':'int32'})
# 01-01-1999, 19990101
member['Birth'] = pd.to_datetime(member['Birth'],
              # format='%Y-%m-%d %H:%M:%S'
              )
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      int32
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int32(1), object(3)
memory usage: 344.0+ bytes

In [10]:
member['year'] = member.Birth.dt.year
member['month'] = member.Birth.dt.month
member['day'] = member.Birth.dt.day

In [11]:
member

   Name  Age          Email  Address      Birth  year  month  day
0   홍길동   20  hong@hong.com  서울시 강동구 1999-01-01  1999      1    1
1   홍길서   30   seo@hong.com   서울시 중구 1999-12-01  1999     12    1
2   홍길남   21   nam@hong.com  서울시 강동구 1999-11-01  1999     11    1
3   홍길북   22   buk@hong.com  서울시 관악구 1999-05-01  1999      5    1
4   홍길중   23   mid@hong.com   부산시 중구 1999-01-30  1999      1   30
5  #홍길뜽   24    non@not.com      없는구 2000-01-01  2000      1    1

In [12]:
current_date = pd.to_datetime('2026-07-15')
member['일수'] = (current_date - member.Birth).dt.days
member

   Name  Age          Email  Address      Birth  year  month  day     일수
0   홍길동   20  hong@hong.com  서울시 강동구 1999-01-01  1999      1    1  10057
1   홍길서   30   seo@hong.com   서울시 중구 1999-12-01  1999     12    1   9723
2   홍길남   21   nam@hong.com  서울시 강동구 1999-11-01  1999     11    1   9753
3   홍길북   22   buk@hong.com  서울시 관악구 1999-05-01  1999      5    1   9937
4   홍길중   23   mid@hong.com   부산시 중구 1999-01-30  1999      1   30  10028
5  #홍길뜽   24    non@not.com      없는구 2000-01-01  2000      1    1   9692

In [15]:
# (2) 특정행을 제외하고 cp949 encoding 파일 읽어오기
member = pd.read_csv('data/ch11_membercp949.csv',
                    encoding='cp949',
                    skiprows=[1, 6]) # 1,6행 제외하고 읽기
member

  Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [22]:
# (3) sep='|', 주석(#)제외, 상위 몇행만, datetime형 필드지정
member_df = pd.read_csv('data/ch11_membersep.csv',
                       sep='|',               # |기준으로 데이터를 분리해서 읽기
                       comment='#',           # #이 있는 행은 제외하고 읽기
                       nrows=3,               # 상위 3행만 읽기
                       parse_dates=['Birth']) #datetime형으로 읽어올 필드 지정
member_df

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [23]:
member_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      object
 1   Age      3 non-null      int64
 2   Email    3 non-null      object
 3   Address  3 non-null      object
 4   Birth    3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 248.0+ bytes

In [26]:
member_df = pd.read_csv('data/ch11_membertab.csv',
                       sep='\t',
                       comment='#',
                       parse_dates=['Birth'])
member_df

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

## 2.4 패키지에서 가져오기 : iris데이터
- iris가져오기 방법1 : sklearn(머신러닝 패키지)
- iris가져오기 방법2 : statsmodels (R 데이터)
- iris가져오기 방법3 : seaborn(시각화 패키지)

## 2.4.1 iris방법1 : sklearn
- sklearn.datasets 모듈 데이터(iris)를 데이터프레임으로 변환

In [28]:
from sklearn import datasets
# import sklearn.datasets as datasets : 머신러닝을 공부하기 위한 학습용 데이터셋을 제공
# sklearn 패키지의 데이터셋 : 독립변수(입력변수)와 종속변수(타겟변수)가 분리된 딕셔너리 형태 제공
iris = datasets.load_iris() # 딕셔너리형태
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [29]:
print(iris.DESCR) # iris 데이터셋에 대한 설명

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica

    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
    :Class Distribution: 33.3% for each of 3 classes.
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. topic:: References

   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
     Mathematical Statistics" (John Wiley, NY, 1950).
   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
     Structure and Classification Rule for Recognition in Partially Exposed
     Environments".  IEEE Transactions on Pattern Analysis and Machine
     Intelligence, Vol. PAMI-2, No. 1, 67-71.
   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
     on Information Theory, May 1972, 431-433.
   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
     conceptual clustering system finds 3 classes in the data.
   - Many, many more ...

In [32]:
iris.data # 독립변수
iris['data'][:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [35]:
iris.feature_names # 독립변수의 열이름
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [43]:
# 데이터프레임에서 독립변수 열이름
[col[:-5].replace(' ', '_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [44]:
[col[:12].strip().replace(' ', '_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [46]:
# 종속변수(타겟변수)
iris.target
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [48]:
iris.target_names
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [51]:
# 데이터프레임에 가장 오른쪽 열(타겟변수-species)
iris.target_names[iris.target]
iris['target_names'][iris['target']]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica'], dtype='<U10')

In [57]:
# 독립변수 : [col[:-5].replace(' ', '_') for col in iris.feature_names]
data = iris.data
print(data[::50])
# 종속변수 : species
target = iris.target_names[iris.target].reshape(-1, 1)
print(target[::50])

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]
[['setosa']
 ['versicolor']
 ['virginica']]

In [59]:
print('독립변수의 차원 :', data.shape)
print('종속변수의 차원 :', target.shape)

독립변수의 차원 : (150, 4)
종속변수의 차원 : (150, 1)

In [66]:
# ⓐ 독립변수, 종속변수를 stack한 후, 데이터프레임으로 생성
import numpy as np
df = pd.DataFrame(np.hstack( (data, target) ),
                 columns=[col[:-5].replace(' ', '_') for col in iris.feature_names] + ['species'])
df.head(3) # 상위 5행만

  sepal_length sepal_width petal_length petal_width species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa

In [69]:
df['petal_width']
df.petal_width[:3]

0    0.2
1    0.2
2    0.2
Name: petal_width, dtype: object

In [71]:
df = pd.DataFrame(np.hstack( (data, target) ),
                 columns=iris.feature_names + ['species'])
df.head(3)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa

In [75]:
df['petal width (cm)'][:3]
#df.petal width (cm)

0    0.2
1    0.2
2    0.2
Name: petal width (cm), dtype: object

In [80]:
# ⓑ 독립변수, 종속변수를 따로 데이터프레임으로 생성한후 두 데이터프레임을 연결
# X : 독립변수 데이터프레임
X = pd.DataFrame(data, 
                 columns=[col[:-5].replace(' ', '_') for col in iris.feature_names])
X.head(1)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [83]:
# y : 종속변수 데이터프레임
y = pd.DataFrame(target, columns=['species'])
y.tail() # 하위 5줄

       species
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

In [85]:
print(X.index) # index:행이름
print(y.index)

RangeIndex(start=0, stop=150, step=1)
RangeIndex(start=0, stop=150, step=1)

In [88]:
# 두 데이터 프레임을 연결(열로 연결)
iris_df = pd.concat( [X, y] , axis=1)

In [91]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB